In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('migros.csv')
df = df[['formatted_address', 'name', 'rating', 'user_ratings_total', 'geometry.location.lat', 'geometry.location.lng']]
df.head()

,formatted_address,name,rating,user_ratings_total,geometry.location.lat,geometry.location.lng
0,"Badenerstrasse 376, 8004 Zürich, Switzerland",Migros Supermarkt,4.1,463,47.379105,8.508754
1,"Birmensdorferstrasse 140, 8003 Zürich, Switzer...",Migros Supermarkt,4.2,636,47.370066,8.520107
2,"Birmensdorferstrasse 320, 8055 Zürich, Switzer...",Migros Supermarkt,4.3,520,47.369956,8.508721
3,"Etzelstrasse 3, 8038 Zürich, Switzerland",Migros Supermarkt,4.3,616,47.344706,8.529962
4,"Falkenstrasse 19 - 21, 8008 Zürich, Switzerland",Migros,4.2,419,47.365446,8.547967

In [7]:
df.columns = ['address', 'name', 'rating', 'users_rating_num', 'lat', 'lng']
df.head()

,address,name,rating,users_rating_num,lat,lng
0,"Badenerstrasse 376, 8004 Zürich, Switzerland",Migros Supermarkt,4.1,463,47.379105,8.508754
1,"Birmensdorferstrasse 140, 8003 Zürich, Switzer...",Migros Supermarkt,4.2,636,47.370066,8.520107
2,"Birmensdorferstrasse 320, 8055 Zürich, Switzer...",Migros Supermarkt,4.3,520,47.369956,8.508721
3,"Etzelstrasse 3, 8038 Zürich, Switzerland",Migros Supermarkt,4.3,616,47.344706,8.529962
4,"Falkenstrasse 19 - 21, 8008 Zürich, Switzerland",Migros,4.2,419,47.365446,8.547967

In [9]:
df.to_csv('Migros_modified.csv')

In [33]:
# read other files
df_all = pd.DataFrame()
supermarket_name = ['Coop', 'Denner', 'Aldi', 'Lidl','Spar']
for i in range(len(supermarket_name)):
    df = pd.read_csv(f'{name[i]}.csv')
    df = df[['formatted_address', 'name', 'rating', 'user_ratings_total', 'geometry.location.lat', 'geometry.location.lng']]
    df.columns = ['address', 'name', 'rating', 'users_rating_num', 'lat', 'lng']
    df['name_s']=name[i]
    df_all = df_all.append(df)

In [34]:
df_all.to_csv('Competitor_modified.csv')